### ISSUE TITLE
 undefined is not a function

### ISSUE THREAD

**Issue by iveoles** [TylerGarlick/angular-redactor#11]
Hi

I'm getting an error on a new install, from what I can tell I have everything installed ok. Do you know what would cause this?

Here is the error

```
TypeError: undefined is not a function
    at http://dev.rvwd.com/js/angular-redactor.js:36:32
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.10/angular.min.js:113:78
    at e (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.10/angular.min.js:33:287)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.10/angular.min.js:37:1 
```

It seems to be this line

```
$timeout(function () {
        editor = $_element.redactor(options);
        ngModel.$render();
      });
```

**Comment by kotmatpockuh** [comment]
getting same:

`
TypeError: undefined is not a function
    at angular-redactor.js:55
    at angular.js:16223
    at completeOutstandingRequest (angular.js:4905)
    at angular.js:5285angular.js:11607 (anonymous function)angular.js:8557 $getangular.js:16226 (anonymous function)angular.js:4905 completeOutstandingRequestangular.js:5285 (anonymous function)
`
